### ISSUE TITLE
Cold water coral mounds

### ISSUE THREAD

**Issue by pieterprovoost** [iobis/datarescue#8]
https://www.frontiersin.org/articles/10.3389/fmars.2019.00184/full

**Comment by sformel-usgs** [comment]
@pieterprovoost I was intrigues to see this under `datarescue` instead of `dataqueue`, since it's a relatively recent paper.  Are the authors unwilling to share the original data?

@RobertMcGuinn do you have any knowledge of this dataset or the data generators?  I don't see it, or any other data around Rockall bank, in your portal currently.  If y'all have any connections to help mobilize it, let's do some collaboration!

**Comment by RobertMcGuinn** [comment]
I'm not familiar with that dataset, but I'm good with pursuing.  I have attended a couple of conferences with Tina N. Molodtsova and J. Murray Roberts.  I would be surprised if they are unwilling to share the data with GBIF.  I'm willing to reach out to them if you think it would be useful.

**Comment by sformel-usgs** [comment]
Thanks, that would be good to reach out. If you don't mind flying the OBIS flag on this one, I'd appreciate it.  We'll also publish to GBIF, but it makes more sense for it to fall under OBIS first.

**Comment by RobertMcGuinn** [comment]
Right on.

**Comment by sformel-usgs** [comment]
We received a response from Laurence DeClippele:
> The data is already published and can be found on PANGAEA here: [https://doi.pangaea.de/10.1594/PANGAEA.909118](https://doi.pangaea.de/10.1594/PANGAEA.909118)
...I am happy for this to be added to the OBIS and NOAA portal too.

@RobertMcGuinn transformed this data to according to the DSCRTP schema (see [code](https://github.com/RobertMcGuinn/deepseatools/blob/master/code/20231121-0_Laurence_Helene_De_Clippele_RPMcGuinn.R)) and is being added to the [DSCRTP](https://deepseacoraldata.noaa.gov/).

and the data will be published to OBIS as part of the next [DSCRTP dataset](https://obis.org/dataset/f5a4799e-dc24-4807-89d9-01da47d52e3b) update ~ January 2024.

**Comment by sformel-usgs** [comment]
@pieterprovoost I don't think I have permissions to close this, but it can be closed when you have a moment.

**Comment by pieterprovoost** [comment]
Great, thanks @sformel-usgs !
